In [1]:
import torch


In [4]:
x = torch.rand((2, 3))
x

tensor([[0.8359, 0.4783, 0.5318],
        [0.5830, 0.8979, 0.5588]])

In [5]:
# permutation of tensor
torch.einsum('ij->ji', x)

#general alternative for transpose for multiple dimensions

tensor([[0.8359, 0.5830],
        [0.4783, 0.8979],
        [0.5318, 0.5588]])

In [6]:
#total summation
torch.einsum('ij->', x)

tensor(3.8856)

In [7]:
# col sum -> 2nd rule sum over that dimension which is not specified
torch.einsum('ij->j', x)

tensor([1.4189, 1.3762, 1.0906])

In [8]:
# row sum
torch.einsum('ij->i',x)

tensor([1.8459, 2.0397])

In [9]:
# matrix - vector multiplication
v = torch.rand((1, 3))
v

tensor([[0.2965, 0.6978, 0.1236]])

In [15]:
# we would do torch.matmul(x, v.t())
torch.einsum('ij, kj-> ik', x, v)
# we can just speccify the dimensions as we would like do not worry about reshaping

tensor([[0.6473],
        [0.8685]])

In [16]:
# matrix multiplication x.mm(x.t())
torch.einsum('ij, kj->ik',x, x) # 2x2: 2x3 X 3x2

tensor([[1.2102, 1.2139],
        [1.2139, 1.4584]])

In [17]:
# dot product first row with first row of matrix

torch.einsum("i, i->", x[0], x[0]) #multiply them and sum together 

tensor(1.2102)

In [18]:
# dot product with a matrix
torch.einsum('ij, ij->', x, x) # multiply those dimensions elemet wise and sum those as we are not specifying any output dimension

tensor(2.6686)

In [19]:
# hadamard product (element wise multiplication)
torch.einsum("ij, ij-> ij", x,x)

tensor([[0.6987, 0.2287, 0.2828],
        [0.3399, 0.8063, 0.3122]])

In [22]:
# outer product
a = torch.rand((3))
b = torch.rand((5))
print(a,b)

tensor([0.0669, 0.4257, 0.1284]) tensor([0.5581, 0.0114, 0.3320, 0.1336, 0.0481])


In [23]:
torch.einsum('i,j->ij',a, b)

tensor([[0.0373, 0.0008, 0.0222, 0.0089, 0.0032],
        [0.2376, 0.0049, 0.1413, 0.0569, 0.0205],
        [0.0717, 0.0015, 0.0426, 0.0172, 0.0062]])

In [24]:
# batch matrix multiplication
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))

In [27]:
print(a)

tensor([[[0.4439, 0.8518, 0.0274, 0.4039, 0.9516],
         [0.1949, 0.9648, 0.4507, 0.6531, 0.1269]],

        [[0.8611, 0.3240, 0.7792, 0.3529, 0.8670],
         [0.8588, 0.6474, 0.6506, 0.8270, 0.0866]],

        [[0.4222, 0.0063, 0.0337, 0.5152, 0.3265],
         [0.9707, 0.5304, 0.7236, 0.7062, 0.1349]]])


In [28]:
print(b)

tensor([[[0.0838, 0.3579, 0.3544],
         [0.6477, 0.4894, 0.2690],
         [0.6090, 0.3690, 0.7000],
         [0.9438, 0.5963, 0.6871],
         [0.0942, 0.5759, 0.7145]],

        [[0.4368, 0.4101, 0.9316],
         [0.3672, 0.5902, 0.3404],
         [0.6847, 0.2392, 0.0487],
         [0.5589, 0.1860, 0.7142],
         [0.6228, 0.8077, 0.7029]],

        [[0.2053, 0.1460, 0.2728],
         [0.2852, 0.8216, 0.6679],
         [0.5862, 0.7638, 0.1191],
         [0.2173, 0.2636, 0.5727],
         [0.7716, 0.6807, 0.8176]]])


In [25]:
torch.einsum("ijk, ikl->ijl", a, b) # here i and k needs to match
# we can also to torch.bmm

tensor([[[1.0765, 1.3747, 1.3631],
         [1.5441, 1.1708, 1.1835]],

        [[1.7659, 1.4967, 1.8119],
         [1.5746, 1.1136, 1.7037]],

        [[0.4721, 0.4506, 0.6854],
         [1.0323, 1.4081, 1.2199]]])

In [29]:
#matrix diagonal
x = torch.rand((3,3))
x

tensor([[0.6032, 0.2361, 0.4647],
        [0.2148, 0.2407, 0.6258],
        [0.0011, 0.2426, 0.1901]])

In [30]:
torch.einsum("ii->i",x)

tensor([0.6032, 0.2407, 0.1901])

In [31]:
# matrix trace
torch.einsum("ii->",x)

tensor(1.0340)